import { Hono } from 'hono';
import { adminRoutes } from './admin.js';
import { benchmarkRoutes } from './benchmarks.js';
import { delayPredictionRoutes } from './delay-prediction.js';
import { complianceRoutes } from './compliance.js';
import { feedbackRoutes } from './feedback.js';
import { googleCalendarRoutes } from './google-calendar.js';
import { legalRoutes } from './legal.js';
import { dashboardRoutes } from './dashboard.js';
import { notificationRoutes } from './notifications.js';
import { docsRoutes } from './docs.js';
import { graphRoutes } from './graph.js';
import { insightRoutes, intelligenceAdminRoutes } from './insights.js';
import { ingestionAdminRoutes } from './ingestion-admin.js';
import { meRoutes } from './me.js';
import { operationalRoutes } from './operational.js';
import { integrationSetupRoutes } from './integration-setup.js';
import { jiraRoutes } from './jira.js';
import { linearRoutes } from './linear.js';
import { hubspotRoutes } from './hubspot.js';
import { microsoftDynamicsRoutes } from './microsoft-dynamics.js';
import { pipedriveRoutes } from './pipedrive.js';
import { salesforceRoutes } from './salesforce.js';
import { slackRoutes } from './slack.js';
import { tenantRoutes } from './tenants.js';
import { riskAdminRoutes } from './risks-admin.js';
import { outboundWebhookRoutes } from './outbound-webhooks.js';
import { webhookRoutes } from './webhooks.js';

export const v1Routes = new Hono();

v1Routes.route('/', meRoutes);
v1Routes.route('/', tenantRoutes);
v1Routes.route('/', operationalRoutes);
v1Routes.route('/', dashboardRoutes);
v1Routes.route('/', notificationRoutes);
v1Routes.route('/', complianceRoutes);
v1Routes.route('/', benchmarkRoutes);
v1Routes.route('/', delayPredictionRoutes);
v1Routes.route('/', feedbackRoutes);
v1Routes.route('/', legalRoutes);
v1Routes.route('/', integrationSetupRoutes);
v1Routes.route('/', salesforceRoutes);
v1Routes.route('/', hubspotRoutes);
v1Routes.route('/', microsoftDynamicsRoutes);
v1Routes.route('/', pipedriveRoutes);
v1Routes.route('/', jiraRoutes);
v1Routes.route('/', linearRoutes);
v1Routes.route('/', slackRoutes);
v1Routes.route('/', googleCalendarRoutes);
v1Routes.route('/', adminRoutes);
v1Routes.route('/', ingestionAdminRoutes);
v1Routes.route('/', graphRoutes);
v1Routes.route('/', insightRoutes);
v1Routes.route('/', intelligenceAdminRoutes);
v1Routes.route('/', riskAdminRoutes);
v1Routes.route('/', outboundWebhookRoutes);
v1Routes.route('/', webhookRoutes);
v1Routes.route('/', docsRoutes);
